Repository SONGS4RI/webserv, pull requests merged in 2024-03, with the labels that each got.

#23 Socket manager 완료
  modules/Client.cpp
  modules/Client.hpp
  modules/Makefile
  modules/Request.hpp
  modules/Response.cpp
  modules/Server.cpp
  modules/Server.hpp
  modules/SocketManager.cpp
  modules/SocketManager.hpp
  modules/main.cpp
Labels: enhancement, refactoring

#26 :sparkles: [Feature] Cgi 핸들 완료
  jahlee/forkTest.cpp
  modules/RequestHandler.cpp
  modules/cgi/main.py
  modules/request_handler/RequestHandler.cpp
  modules/request_handler/RequestHandler.hpp
  modules/response/Response.hpp
  modules/response/ResponseBody.hpp
  modules/server/Client.cpp
  modules/server/Client.hpp
  modules/server/EventManager.cpp
  modules/server/SocketManager.cpp
  modules/server/SocketManager.hpp
  root/html/400.html
  root/html/404.html
  root/html/405.html
  root/html/500.html
  root/html/default.html
Labels: enhancement

#28 :hammer: refactor: 컴파일 되게 수정.
  modules/Makefile
  modules/configuration_example/test.conf
  modules/request/Request.cpp
  modules/request/RequestBody.cpp
  modules/response/ResponseBody.cpp
  modules/response/ResponseBody.hpp
  modules/server/Client.cpp
  modules/server/Client.hpp
Labels: refactoring

#29 :sparkles: [Feature] utils static 함수로 변경
  modules/main.cpp
  modules/parseConfig/Config.cpp
  modules/parseConfig/ParseConfig.cpp
  modules/request_handler/RequestHandler.cpp
  modules/response/Response.cpp
  modules/server/EventManager.cpp
  modules/server/Server.cpp
  modules/server/SocketManager.cpp
  modules/utils/Utils.cpp
  modules/utils/Utils.hpp
Labels: refactoring

#31 :sparkles: [Feature] 로깅 함수 세팅
  modules/main.cpp
  modules/utils/Utils.cpp
  modules/utils/Utils.hpp
Labels: enhancement

#34 :sparkles: [Feature] 자잘한 수정 + 로깅 문구 추가
  modules/request/Request.cpp
  modules/server/Client.cpp
  modules/server/EventManager.cpp
  modules/server/SocketManager.cpp
Labels: refactoring

#45 :sparkles: [Feature] post html 추가
  configuration_example/default.conf
  root/html/default.html
  root/html/post.html
Labels: enhancement

#47 1차 완성. test 요망
  modules/cgi/main.py
  modules/request/Request.cpp
  modules/request/Request.hpp
  modules/request/RequestBody.cpp
  modules/request/RequestBody.hpp
  modules/request_handler/RequestHandler.cpp
Labels: enhancement

#48 POST OCTECT html에러 제대로 안뜸.
  .vscode/settings.json
  configuration_example/default.conf
  modules/config/Config.cpp
  modules/config/Config.hpp
  modules/request/Request.cpp
  modules/request_handler/RequestHandler.cpp
  modules/response/ResponseBody.hpp
  modules/server/EventManager.cpp
  root/delete/test.txt
  root/html/test/empty
Labels: refactoring

#49 :hammer: [Refactoring] html 수정
  configuration_example/default.conf
  root/html/default.html
Labels: refactoring
